# Generated by Django 3.1.1 on 2022-07-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={},
        ),
    ]
